############################ Default configuration #########################
baseURL = "https://camilovarela.github.io/"
languageCode = "en-us"
# site title 
title = "Northendlab | Blog Template"

# theme
theme = "northendlab-hugo"
# post pagination
paginate = "5"

# post excerpt
summaryLength = "10"

# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com

[outputs]
home = ["HTML", "AMP", "RSS", "JSON"]

########################## Plugings ######################################

# css plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"

# js plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search.js"


########################### Navigation ###################################

# main menu
#[[menu.main]]
#URL = "contact"
#name = "Contact"
#weight = 1

[[menu.main]]
URL = "about-me"
name = "About me"
weight = 1

#[[menu.main]]
#URL = "tools"
#name = "tools"
#weight = 2

# footer menu
#[[menu.footer]]
#URL = "contact"
#name = "Contact"
#weight = 1


######################### Default Parameters ###########################
[params]
# home
home = "Home"
# logo
logo = "images/logo.svg"
# meta data
author = "Themefisher"
description = "This is meta description"
# google tag manager
google_tag_manager = "" # your id
# contact form action
contact_form_action = "#" # contact form works with : https://formspree.io
# copyright
copyright = "&copy; 2021 [Gethugothemes](https://gethugothemes.com) All Rights Reserved"

# preloader
[params.preloader]
enable = true
preloader = "" # use png, jpg, svg or gif format

# search
[params.search]
enable = true

# cookies
[params.cookies]
enable = true
expire_days = 2

####################### banner #######################################
[params.banner]
bgImage = "images/banner/banner-bg.svg"
title = "Hi, I'm a Software Developer who loves building stuff with ❤️"
image = "images/banner/illustration.svg"


######################## call to action ###############################
[params.cta]
enable = true
image = "images/hugo-logo-wide.svg"
title = "Let's learn about Hugo"
description = "Hugo is one of the most popular open-source static site generators. With its amazing speed and flexibility, Hugo makes building websites fun again."
[params.cta.button]
enable = true
label = "Visit Here"
link = "https://gohugo.io/"


############################## Social Site ##########################
[[params.social]]
icon = "ti-github" # themify icon pack https://themify.me/themify-icons
link = "https://github.com/camilovarela"
[[params.social]]
icon = "ti-linkedin" # themify icon pack https://themify.me/themify-icons
link = "https://www.linkedin.com/in/camilovarela/"